# Generated by Django 5.0.4 on 2024-05-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('tasks', models.JSONField(default=[])),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('text', models.TextField(max_length=1000)),
                ('ans_type', models.CharField(choices=[('C', 'Answer as code'), ('T', 'Answer as text')], default='T', max_length=1)),
                ('ref_ans', models.CharField(max_length=256, null=True)),
                ('tests', models.JSONField(default=[], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('test_input', models.TextField()),
                ('test_output', models.TextField()),
            ],
        ),
    ]
