# Generated by Django 5.0.4 on 2024-05-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_edu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='tasks',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='task',
            name='tests',
            field=models.JSONField(default=list, null=True),
        ),
    ]
