# Generated by Django 5.0.4 on 2024-05-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_edu', '0003_alter_contest_name_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='ans_type',
            field=models.CharField(choices=[('C', 'Answer as code'), ('T', 'Answer as text')], default='C', max_length=1),
        ),
    ]
