# Generated by Django 5.0.6 on 2024-05-17 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_edu', '0005_alter_contest_id_alter_task_id_alter_test_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='linked_contest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_edu.contest'),
        ),
        migrations.AddField(
            model_name='test',
            name='linked_task',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='django_edu.task'),
        ),
    ]
